#! /usr/bin/python2

#######################################################################
# This file is part of ncmultipyng
#
# Copyright (C) 2014 Nicolas Pillot
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#######################################################################

import argparse
import re
import subprocess
import time
import os

#######################################################################
# Target host
#######################################################################

# host class to store target information
class Host:

	# ipv4 and ipv6 regexp courtesy of
	# http://www.sroze.io/2008/10/09/regex-ipv4-et-ipv6/
	_pattern_ipv4 = (
		"("
			"(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\."
			"(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\."
			"(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\."
			"(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)"
		")"
	)
	_pattern_ipv6 = (
		"("
			"("
				"([0-9A-Fa-f]{1,4}:){7}"
				"[0-9A-Fa-f]{1,4}"
			")|"
			"("
				"([0-9A-Fa-f]{1,4}:){6}"
				":"
				"[0-9A-Fa-f]{1,4}"
			")|"
			"("
				"([0-9A-Fa-f]{1,4}:){5}"
				":"
				"([0-9A-Fa-f]{1,4}:)?"
				"[0-9A-Fa-f]{1,4}"
			")|"
			"("
				"([0-9A-Fa-f]{1,4}:){4}"
				":"
				"([0-9A-Fa-f]{1,4}:){0,2}"
				"[0-9A-Fa-f]{1,4}"
			")|"
			"("
				"([0-9A-Fa-f]{1,4}:){3}"
				":"
				"([0-9A-Fa-f]{1,4}:){0,3}"
				"[0-9A-Fa-f]{1,4}"
			")|"
			"("
				"([0-9A-Fa-f]{1,4}:){2}"
				":"
				"([0-9A-Fa-f]{1,4}:){0,4}"
				"[0-9A-Fa-f]{1,4}"
			")|"
			"("
				"([0-9A-Fa-f]{1,4}:){6}"
				"((b((25[0-5])|(1d{2})|(2[0-4]d)|(d{1,2}))b).){3}"
				"(b((25[0-5])|(1d{2})|(2[0-4]d)|(d{1,2}))b)"
			")|"
			"("
				"([0-9A-Fa-f]{1,4}:){0,5}:"
				"((b((25[0-5])|(1d{2})|(2[0-4]d)|(d{1,2}))b).){3}"
				"(b((25[0-5])|(1d{2})|(2[0-4]d)|(d{1,2}))b)"
			")|"
			"("
				"::"
				"([0-9A-Fa-f]{1,4}:){0,5}"
				"((b((25[0-5])|(1d{2})|(2[0-4]d)|(d{1,2}))b).){3}"
				"(b((25[0-5])|(1d{2})|(2[0-4]d)|(d{1,2}))b)"
			")|"
			"("
				"[0-9A-Fa-f]{1,4}"
				"::"
				"([0-9A-Fa-f]{1,4}:){0,5}"
				"[0-9A-Fa-f]{1,4}"
			")|"
			"("
				"::"
				"([0-9A-Fa-f]{1,4}:){0,6}"
				"[0-9A-Fa-f]{1,4}"
			")|"
			"("
				"([0-9A-Fa-f]{1,4}:){1,7}"
				":"
			")"
		")"
	)
	_re_ipv4 = re.compile(_pattern_ipv4 + "$")
	_re_ipv6 = re.compile(_pattern_ipv6 + "$", re.IGNORECASE)

	# constructor
	def __init__(self, string):
		self.address = None
		self.version = None
		self.process = None
		self._parse_ip(string)

	# print
	def __repr__(self):
		return "Host(address=%s,version=%s)" % (self.address, self.version)

	# parse ip
	def _parse_ip(self, string):
		result = self._re_ipv4.match(string)
		if result is not None:
			self.version = 4
			self.address = result.group()
			return
		result = self._re_ipv6.match(string)
		if result is not None:
			self.version = 6
			self.address = result.group()
			return
		message = "%s is not a valid host definition" % string
		raise argparse.ArgumentTypeError(message)

	# finished process
	def finished(self,retcode):
		print "%s returned  %s" % (self.address, retcode)

	# spawn process
	def spawn(self,args):

		if self.process is not None:
			retcode = self.process.poll()
			if retcode is None:
				return
			self.finished(retcode)
			self.process = None

		if self.version == 6:
			cmd = "ping6"
		else:
			cmd = "ping"
		timeout = args.i - 1
		if timeout <= 0:
			timeout = 1
		params = [
			cmd,
			"-q", "-n",
			"-W", str(timeout),
			"-c", "1",
			self.address
		]
		with open(os.devnull, "w") as f:
			self.process = subprocess.Popen(params,stdout=f,stderr=f)

#######################################################################
# Command line arguments
#######################################################################

class Arguments:

	def range_integer(self, parser, string, name, mini=None, maxi=None):
		value = int(string)
		if mini is not None and value < mini:
			parser.error(
				"%s=%s is below the minimum value of %i"
				% (name, string, mini)
			)
		if maxi is not None and value > maxi:
			parser.error(
				"%s=%s is above the maximum value of %i"
				% (name, string, maxi)
			)
		return value

	def __init__(self):
		parser = argparse.ArgumentParser()
		parser.add_argument(
			"host",
			help = "target host definition (IPv4/IPv6)",
			action = "store",
			nargs = "+",
			type = lambda x: Host(x)
		)
		parser.add_argument(
			"-i",
			help = "polling interval in seconds",
			action = "store",
			default = 3,
			type = lambda x:
				self.range_integer(
					parser, x,
					"interval", 1, None
				)
		)
		self.data = parser.parse_args()

	# print
	def __repr__(self):
		return "Arguments=%s" % self.data

#######################################################################       
# Application
#######################################################################

class Application:

	# constructor
	def __init__(self):

		# analyze and parse arguments
		self.arguments = Arguments()
		print self.arguments

		# move around data references
		self.hosts = self.arguments.data.host
		del self.arguments.data.host

	# ping all addresses
	def pingall(self):
		for host in self.hosts:
			host.spawn(self.arguments.data)

	# sleep for the interval
	def sleep(self):
		time.sleep(self.arguments.data.i)

	# main loop
	def run(self):
		while True:
			self.pingall()
			self.sleep()

#######################################################################
# main
#######################################################################

app = Application()
try:
	app.run()
except (KeyboardInterrupt, SystemExit):
	pass
